config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'articles#index'
  resources :articles, only: [:index, :show, :alimentacao]

  get 'alimentacao', to: 'articles#alimentacao'
  get 'desporto', to: 'articles#desporto'

  get 'home', to: 'pages#home', as: :home

  namespace :admin do
    resources :articles
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments, as: :commentable
  has_many :photos
  validates :subject, :title, :body, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable
  validates :body, presence: true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :article
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  validates :email, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show]
  skip_before_action :authenticate_user!, only: [:index, :show, :alimentacao]

  def index
    @articles = policy_scope(Article).order(created_at: :desc).limit(3)
  end

  def show
  end

  def alimentacao
    if params["filter"].nil?
      @articles = policy_scope(Article).where(subject: :alimentacao).order(created_at: :desc)
    else
      @filter = params["filter"]
      @articles = policy_scope(Article)
      # @articles = @articles.where('subject ILIKE ?', "%#{@filter}%") if @filter.present?
    end
  end

  def desporto
    @articles = policy_scope(Article).where(subject: :desporto).order(created_at: :desc)
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:subject, :filter)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/alimentacao.html.erb
<img src="https://images.unsplash.com/photo-1502741126161-b048400d085d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2250&q=80" alt="" class="homepage-first-image">
<div class="container">
  <%= simple_form_for :filter, url: {controller: 'articles', action: 'alimentacao'}, method: :get do |f| %>
    <%= f.input :subject, as: :select, required: false, collection: %w[Pequeno-Almoço Almoço/Jantar Snacks] %>
    <%= f.submit :SEARCH, class: "btn-form" %>
  <% end %>
  <% @articles.each do |art| %>
    <%= link_to article_path(art) do %>
    <div class="card-trip">
      <div class="card-trip-infos">
        <img src="https://images.unsplash.com/photo-1504754524776-8f4f37790ca0?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2250&q=80" alt="">
        <div class=>
          <div class="w-100">
            <h2><%= art.title %></h2>
            <p><%= art.caption %></p>
          </div>
          <div class="d-flex align-items-center w-100 card-trip-author">
            <img src="https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2250&q=80" alt=""  class="card-trip-user avatar-bordered">
            <p><%= art.author %></p>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  <% end %>
</div>

app/views/articles/desporto.html.erb
<img src="https://images.unsplash.com/photo-1502741126161-b048400d085d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2250&q=80" alt="" class="homepage-first-image">
<div class="container">
  <% @articles.each do |art| %>
    <%= link_to article_path(art) do %>
    <div class="card-trip">
      <div class="card-trip-infos">
        <img src="https://images.unsplash.com/photo-1504754524776-8f4f37790ca0?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2250&q=80" alt="">
        <div class=>
          <div class="w-100">
            <h2><%= art.title %></h2>
            <p><%= art.caption %></p>
          </div>
          <div class="d-flex align-items-center w-100 card-trip-author">
            <img src="https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2250&q=80" alt=""  class="card-trip-user avatar-bordered">
            <p><%= art.author %></p>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  <% end %>
</div>

app/views/articles/index.html.erb
<img src="https://images.unsplash.com/photo-1578687595055-d15759a04151?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2250&q=80" alt="" class="homepage-first-image">
<div class="container">
  <% @articles.each do |art| %>
    <%= link_to article_path(art) do %>
    <div class="card-trip">
      <div class="card-trip-infos">
        <img src="https://images.unsplash.com/photo-1578687595055-d15759a04151?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2250&q=80" alt="">
        <div class=>
          <div class="w-100">
            <h2><%= art.title %></h2>
            <p><%= art.caption %></p>
          </div>
          <div class="d-flex align-items-center w-100 card-trip-author">
            <img src="https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2250&q=80" alt=""  class="card-trip-user avatar-bordered">
            <p><%= art.author %></p>
          </div>
        </div>
      </div>
    </div>

    <% end %>
  <% end %>

app/views/articles/show.html.erb
<div class="container">
  <img src="https://images.unsplash.com/photo-1504754524776-8f4f37790ca0?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2250&q=80" alt="" class="homepage-first-image">
  <h1><%= @article.title %></h1>
  <h3><%= @article.caption %></h3>
  <p><%= @article.body %></p>
  <p><%= @article.author %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>LYA - Blog</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="cards">
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
    Pequeno-Almoço
  </div>
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/lunch.jpg)">
    Almoço/jantar
  </div>
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/dinner.jpg)">
    Snacks
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer was made with <i class="fas fa-heart"></i> by Marta
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to articles_path , class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="menu-centro">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Alimentação", alimentacao_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Desporto", desporto_path, class: "nav-link" %>
      </li>
    </ul>
  </div>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
<!--         <li class="nav-item active">
          <%#= link_to "Home", articles_path , class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%#= link_to "Messages", "#", class: "nav-link" %>
        </li> -->
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>